services:
  wanzz-ppob:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - wanzz-data:/app/server/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  wanzz-data:
    driver: local
